# Clean BCTC luong2 (2026-04-04)

Notebook nay doc toan bo file du lieu trong thu muc ngay, lam sach theo 3 rule va tra ve mot DataFrame duy nhat: df_clean.

In [38]:
from pathlib import Path
import re
import numpy as np
import pandas as pd
from concurrent.futures import ThreadPoolExecutor # Import thêm thư viện đa luồng

DATA_CANDIDATES = [
    Path(r"d:/project/lakehouse_ptich_ck/test/general/bctc_luong2/2026-04-04"),
    Path(r"d:/project/lakehouse_ptich_ck/etl/minio/data/thongtin-congty-va-bctc/bctc_luong2/2026-04-04"),
]

data_root = next((p for p in DATA_CANDIDATES if p.exists()), None)
if data_root is None:
    raise FileNotFoundError("Khong tim thay thu muc du lieu 2026-04-04.")

def clean_indicator(value: object) -> object:
    if pd.isna(value):
        return value
    text = str(value).strip()
    text = re.sub(r"^\s*=\-\s*", "", text)
    return text

def parse_de_vn_number(value: object) -> float:
    if pd.isna(value):
        return np.nan
    s = str(value).strip()
    if s == "":
        return np.nan
    if s.lower() in {"nan", "none", "null", "n/a", "na", "-", "--"}:
        return np.nan

    negative = False
    if s.startswith("(") and s.endswith(")"):
        negative = True
        s = s[1:-1].strip()

    s = s.replace("\u00A0", "").replace(" ", "")
    s = s.replace("%", "")
    s = re.sub(r"[^0-9,.-]", "", s)

    if "," in s and "." in s:
        s = s.replace(".", "").replace(",", ".")
    elif "," in s:
        s = s.replace(",", ".")
    elif re.fullmatch(r"-?\d{1,3}(?:\.\d{3})+", s):
        s = s.replace(".", "")

    try:
        num = float(s)
        return -num if negative else num
    except ValueError:
        return np.nan

def read_any_table(file_path: Path) -> pd.DataFrame | None:
    try:
        if file_path.suffix.lower() == ".csv":
            try:
                return pd.read_csv(file_path, encoding="utf-8-sig")
            except UnicodeDecodeError:
                return pd.read_csv(file_path, encoding="utf-8")
        if file_path.suffix.lower() in {".xlsx", ".xls"}:
            return pd.read_excel(file_path)
    except Exception as exc:
        print(f"[SKIP] {file_path}: {exc}")
    return None

def normalize_one_df(raw_df: pd.DataFrame, file_path: Path) -> pd.DataFrame:
    df = raw_df.copy()
    df.columns = [str(c).strip() for c in df.columns]

    indicator_col = None
    for c in df.columns:
        if str(c).strip().lower() in {"chi_tieu", "chỉ tiêu", "chi tieu"}:
            indicator_col = c
            break
    if indicator_col is None:
        indicator_col = df.columns[0]

    if indicator_col != "chi_tieu":
        df = df.rename(columns={indicator_col: "chi_tieu"})

    df["chi_tieu"] = df["chi_tieu"].map(clean_indicator)
    df["ticker"] = file_path.parent.name
    df["source_file"] = str(file_path)

    non_value_cols = {"chi_tieu", "ticker", "source_file"}
    value_cols = [c for c in df.columns if c not in non_value_cols]

    for col in value_cols:
        df[col] = df[col].map(parse_de_vn_number)
        df[col] = df[col] 

    if value_cols:
        df = df.dropna(subset=value_cols, how="all")

    return df

# --- HÀM WRAPPER ĐỂ CHẠY ĐA LUỒNG ---
def process_file(fp: Path) -> pd.DataFrame | None:
    """Đọc và normalize 1 file, trả về DataFrame nếu thành công, None nếu rỗng/lỗi."""
    raw = read_any_table(fp)
    if raw is None or raw.empty:
        return None
    cleaned = normalize_one_df(raw, fp)
    if not cleaned.empty:
        return cleaned
    return None
# ------------------------------------

all_files = []
for pattern in ("**/*.csv", "**/*.xlsx", "**/*.xls"):
    all_files.extend(data_root.glob(pattern))

all_files = sorted({p.resolve() for p in all_files})
if not all_files:
    raise FileNotFoundError(f"Khong tim thay file csv/xlsx/xls trong: {data_root}")

dfs = []

# --- ÁP DỤNG THREADPOOLEXECUTOR ---
# Sử dụng max_workers mặc định (thường tối ưu với số nhân CPU hiện có)
print(f"Bắt đầu xử lý đa luồng {len(all_files)} files...")
with ThreadPoolExecutor() as executor:
    # executor.map sẽ trả về kết quả theo đúng thứ tự của all_files
    results = executor.map(process_file, all_files)
    
    for res in results:
        if res is not None:
            dfs.append(res)
# -----------------------------------

if not dfs:
    raise ValueError("Khong co du lieu hop le sau khi doc + clean.")

df_clean = pd.concat(dfs, ignore_index=True, sort=False)
front_cols = [c for c in ["ticker", "source_file", "chi_tieu"] if c in df_clean.columns]
other_cols = [c for c in df_clean.columns if c not in front_cols]
df_clean = df_clean[front_cols + other_cols]

print(f"Data root: {data_root}")
print(f"Tong so file tim thay : {len(all_files):,}")
print(f"So dong sau clean    : {len(df_clean):,}")
print(f"So cot sau clean     : {df_clean.shape[1]:,}")
df_clean.head(20)

Bắt đầu xử lý đa luồng 4269 files...
Data root: d:\project\lakehouse_ptich_ck\test\general\bctc_luong2\2026-04-04
Tong so file tim thay : 4,269
So dong sau clean    : 150,121
So cot sau clean     : 90

,ticker,source_file,chi_tieu,Q4 2021,Q4 2022,Q4 2023,Q4 2024,Q4 2025,Q1 2025,Q2 2025,Q3 2025,Q2 2008,Q3 2008,Q1 2009,Q2 2009,Q3 2009,Q3 2023,Q1 2024,Q2 2024,Q3 2024,Q2 2013,Q3 2013,Q4 2013,Q1 2014,Q2 2014,Q4 2020,Q4 2018,Q1 2019,Q2 2019,Q3 2019,Q1 2020,Q2 1990,Q3 1990,Q3 2002,Q1 2005,Q2 2005,Q3 2005,Q4 2005,Q2 2020,Q3 2020,Q1 2021,Q3 2017,Q4 2017,Q1 2018,Q2 2018,Q1 2016,Q2 2016,Q3 2016,Q4 2016,Q1 2017,Q2 2023,Q1 2022,Q2 2022,Q2 2021,Q3 2021,Q4 2015,Q4 2014,Q1 2015,Q2 2015,Q3 2015,Q3 2018,Q4 2019,Q1 2011,Q2 2011,Q4 2011,Q1 2012,Q2 2012,Q1 2008,Q4 2008,Q3 2012,Q4 2012,Q1 2013,Q3 2022,Q1 2023,Q3 2014,Q2 2017,Q1 2010,Q2 2010,Q3 2010,Q4 2010,Q3 2011,Q4 1990,Q4 2009,Q2 2006,Q3 2006,Q1 2007,Q2 2007,Q3 2007,Q4 2007,Q1 2006
0,A32,D:\project\lakehouse_ptich_ck\test\general\bctc_luong2\2026-04-04\A32\bang_can_doi_ke_toan_A32_Q4_2025.csv,A. Tài sản lưu động và đầu tư ngắn hạn,401956.00,415663.00,377352.00,365284.00,365336.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A32,D:\project\lakehouse_ptich_ck\test\general\bctc_luong2\2026-04-04\A32\bang_can_doi_ke_toan_A32_Q4_2025.csv,I. Tiền và các khoản tương đương tiền,97299.00,57796.00,56204.00,101876.00,29.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A32,D:\project\lakehouse_ptich_ck\test\general\bctc_luong2\2026-04-04\A32\bang_can_doi_ke_toan_A32_Q4_2025.csv,1. Tiền,74299.00,47796.00,43204.00,98376.00,15.71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A32,D:\project\lakehouse_ptich_ck\test\general\bctc_luong2\2026-04-04\A32\bang_can_doi_ke_toan_A32_Q4_2025.csv,2. Các khoản tương đương tiền,23.00,10.00,13.00,3.50,13.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A32,D:\project\lakehouse_ptich_ck\test\general\bctc_luong2\2026-04-04\A32\bang_can_doi_ke_toan_A32_Q4_2025.csv,III. Các khoản phải thu ngắn hạn,112325.00,177262.00,158278.00,115182.00,185188.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,A32,D:\project\lakehouse_ptich_ck\test\general\bctc_luong2\2026-04-04\A32\bang_can_doi_ke_toan_A32_Q4_2025.csv,1. Phải thu ngắn hạn của khách hàng,87.65,136.74,129533.00,98.51,170099.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,A32,D:\project\lakehouse_ptich_ck\test\general\bctc_luong2\2026-04-04\A32\bang_can_doi_ke_toan_A32_Q4_2025.csv,2. Trả trước cho người bán,11.26,5293.00,4658.00,1.93,4489.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,A32,D:\project\lakehouse_ptich_ck\test\general\bctc_luong2\2026-04-04\A32\bang_can_doi_ke_toan_A32_Q4_2025.csv,6. Phải thu ngắn hạn khác,15138.00,37481.00,25868.00,17028.00,12.93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,A32,D:\project\lakehouse_ptich_ck\test\general\bctc_luong2\2026-04-04\A32\bang_can_doi_ke_toan_A32_Q4_2025.csv,7. Dự phòng phải thu ngắn hạn khó đòi,-1723.00,-2252.00,-1781.00,-2286.00,-2.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,A32,D:\project\lakehouse_ptich_ck\test\general\bctc_luong2\2026-04-04\A32\bang_can_doi_ke_toan_A32_Q4_2025.csv,IV. Tổng hàng tồn kho,192226.00,177086.00,159573.00,147476.00,141255.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,A32,D:\project\lakehouse_ptich_ck\test\general\bctc_luong2\2026-04-04\A32\bang_can_doi_ke_toan_A32_Q4_2025.csv,1. Hàng tồn kho,198752.00,180427.00,163.11,151842.00,148426.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,A32,D:\project\lakehouse_ptich_ck\test\general\bctc_luong2\2026-04-04\A32\bang_can_doi_ke_toan_A32_Q4_2025.csv,2. Dự phòng giảm giá hàng tồn kho,-6526.00,-3341.00,-3536.00,-4366.00,-7171.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,A32,D:\project\lakehouse_ptich_ck\test\general\bctc_luong2\2026-04-04\A32\bang_can_doi_ke_toan_A32_Q4_2025.csv,V. Tài sản ngắn hạn khác,105.00,3518.00,3297.00,750.00,9683.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,A32,D:\project\lakehouse_ptich_ck\test\general\bctc_luong2\2026-04-04\A32\bang_can_doi_ke_toan_A32_Q4_2025.csv,1. Chi phí trả trước ngắn hạn,NaN,24.00,481.00,681.00,1276.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,A32,D:\project\lakehouse_ptich_ck\test\general\bctc_luong2\2026-04-04\A32\bang_can_doi_ke_toan_A32_Q4_2025.csv,2. Thuế giá trị gia tăng được khấu trừ,NaN,3389.00,734.00,NaN,8407.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,A32,D:\project\lakehouse_ptich_ck\test\general\bctc_luong2\2026-04-04\A32\bang_can_doi_ke_toan_A32_Q4_2025.csv,3. Thuế và các khoản phải thu Nhà nước,105.00,105.00,2082.00,69.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,A32,D:\project\lakehouse_ptich_ck\test\general\bctc_luong2\2026-04-04\A32\bang_can_doi_ke_toan_A32_Q4_2025.csv,B. Tài sản cố định và đầu tư dài hạn,126175.00,131.79,128082.00,130637.00,125783.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,A32,D:\project\lakehouse_ptich_ck\test\general\bctc_luong2\2026-04-04\A32\bang_can_doi_ke_toan_A32_Q4_2025.csv,II. Tài sản cố định,114254.00,118151.00,113201.00,112309.00,110309.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,A32,D:\project\lakehouse_ptich_ck\test\general\bctc_luong2\2026-04-04\A32\bang_can_doi_ke_toan_A32_Q4_2025.csv,1. Tài sản cố định hữu hình,113977.00,117909.00,112909.00,112093.00,110152.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,A32,D:\project\lakehouse_ptich_ck\test\general\bctc_luong2\2026-04-04\A32\bang_can_doi_ke_toan_A32_Q4_2025.csv,- Nguyên giá,242736.00,252528.00,256418.00,265472.00,275117.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
from pathlib import Path
import re
import pandas as pd
import numpy as np


def parse_quarter_year(col_name: object) -> tuple[int | None, int | None]:
    """
    Trích xuất quý và năm từ tên cột.
    Hỗ trợ các dạng như:
    - Q1 2024
    - Q1_2024
    - 2024 Q1
    """
    s = str(col_name).strip()

    m = re.search(r"[Qq]\s*([1-4])\D*([12]\d{3})", s)
    if m:
        return int(m.group(1)), int(m.group(2))

    m = re.search(r"([12]\d{3})\D*[Qq]\s*([1-4])", s)
    if m:
        return int(m.group(2)), int(m.group(1))

    return None, None


def infer_report_meta(source_file: object) -> tuple[str | None, str | None]:
    """
    Suy ra loại báo cáo từ tên file nguồn.
    """
    file_name = Path(str(source_file)).name.lower()

    if file_name.startswith("bang_can_doi_ke_toan"):
        return "balance_sheet", "BL"
    if file_name.startswith("ket_qua_kinh_doanh"):
        return "income_statement", "IS"
    if file_name.startswith("luu_chuyen_tien_te"):
        return "cash_flow", "CF"

    return None, None


def deep_clean_indicator(text: object) -> str:
    """
    Làm sạch triệt để các ký tự rác và đánh số ở đầu chỉ tiêu.
    """
    if pd.isna(text):
        return ""

    s = str(text).strip()

    # Bước 1: Xóa ký tự rác ở đầu chuỗi
    s = re.sub(r"^[\s=\-\+]+", "", s)

    # Bước 2: Xóa các dạng đánh số đầu dòng
    regex_pattern = (
        r"^("
        r"(?:[a-zA-Z]+)\.\s*"   # A. / B. / I. / II. / a. / b.
        r"|"
        r"(?:\d+\.)+\s*"        # 1. / 2.1. / 1.1.1.
        r"|"
        r"\d+\s*\-\s*"          # 1- / 2 - / 3-
        r")"
    )
    s = re.sub(regex_pattern, "", s)

    # Bước 3: Chạy lại bước 1 phòng trường hợp còn rác
    s = re.sub(r"^[\s=\-\+]+", "", s)

    return s.strip()


# =========================
# BẮT ĐẦU XỬ LÝ DỮ LIỆU
# =========================
if "df_clean" not in globals():
    raise RuntimeError("Không tìm thấy df_clean. Hãy chạy cell clean trước.")


# 1. Xác định cột nền và cột giá trị
base_cols = ["ticker", "source_file", "chi_tieu"]
value_cols = [c for c in df_clean.columns if c not in base_cols]


# 2. Chuyển dữ liệu wide -> long
df_long = df_clean.melt(
    id_vars=base_cols,
    value_vars=value_cols,
    var_name="period_col",
    value_name="value"
).copy()

df_long = df_long.dropna(subset=["value"]).copy()


# 3. Trích xuất quarter / year
qy = df_long["period_col"].map(parse_quarter_year)
df_long["quarter"] = [x[0] for x in qy]
df_long["year"] = [x[1] for x in qy]

df_long = df_long.dropna(subset=["quarter", "year"]).copy()
df_long["quarter"] = df_long["quarter"].astype("int64")
df_long["year"] = df_long["year"].astype("int64")


# 4. Suy ra metadata báo cáo
meta = df_long["source_file"].map(infer_report_meta)
df_long["report_name"] = [x[0] for x in meta]
df_long["report_code"] = [x[1] for x in meta]


# 5. Làm sạch tên chỉ tiêu
df_long["ind_name"] = df_long["chi_tieu"].apply(deep_clean_indicator)

# Loại bỏ các bản ghi lỗi công thức Excel
df_long = df_long[df_long["ind_name"].str.upper() != "#NAME?"].copy()


# 6. Chuẩn hóa cột value về numeric nếu cần
df_long["value"] = pd.to_numeric(df_long["value"], errors="coerce")
df_long = df_long.dropna(subset=["value"]).copy()


# 7. Nếu là bảng cân đối kế toán (BL) thì nhân value với 1 triệu
df_long.loc[df_long["report_code"] == "BL", "value"] = (
    df_long.loc[df_long["report_code"] == "BL", "value"] * 1_000_000
)


# 8. Tạo cột ind_code rỗng để mapping ở bước sau
df_long["ind_code"] = np.nan


# 9. Chọn đúng cấu trúc đầu ra
final_cols = [
    "ticker",
    "quarter",
    "year",
    "ind_name",
    "ind_code",
    "value",
    "report_name",
    "report_code",
]

df_bctc_records = df_long[final_cols].copy()


# 10. Hiển thị kết quả
print(f"Tổng bản ghi chuẩn bị cho bước mapping: {len(df_bctc_records):,}")
pd.set_option("display.max_columns", None)
display(df_bctc_records.head(20))

In [40]:
import pandas as pd

if "df_bctc_records" not in globals():
    raise RuntimeError("Khong tim thay df_bctc_records. Hay chay cell xu ly du lieu truoc.")

# Lấy các giá trị distinct, loại bỏ NaN (nếu có) và sắp xếp
distinct_ind_names = df_bctc_records["ind_name"].dropna().unique()
distinct_ind_names.sort()

# Tạo DataFrame để hiển thị đẹp mắt trong Jupyter Notebook
df_distinct_ind = pd.DataFrame({"ind_name": distinct_ind_names})

print(f"Số lượng chỉ tiêu (ind_name) duy nhất: {len(df_distinct_ind):,}")

# Hiển thị 50 kết quả đầu tiên (bạn có thể thay đổi số lượng nếu cần)
df_distinct_ind.head(20)

# df_distinct_ind.to_csv("distinct_ind_names.csv", index=False, encoding="utf-8-sig")

Số lượng chỉ tiêu (ind_name) duy nhất: 566

                                                                     ind_name
0                                    (+) Tăng, (-) giảm Thuế TNDN CTCK đã nộp
1                   (+) Tăng, (-) giảm phải trả Tổ chức phát hành chứng khoán
2                                   (+) Tăng, (-) giảm phải trả cho người bán
3                                  (+) Tăng, (-) giảm phải trả, phải nộp khác
4                      (+) Tăng, (-) giảm thuế và các khoản phải nộp Nhà nước
5               (- Lãi) hoặc (+ lỗ) chênh lệch tỷ giá hối đoái chưa thực hiện
6             (-) Tăng, (+) giảm các khoản phải thu các dịch vụ CTCK cung cấp
7                                  (-) Tăng, (+) giảm các khoản phải thu khác
8                       (-) Tăng, (+) giảm phải thu bán các tài sản tài chính
9                  (-) Tăng, (+) giảm phải thu tiền lãi các tài sản tài chính
10  (Tăng)/Giảm các công cụ tài chính phái sinh và các tài sản tài chính khác
11                                   (Tăng)/Giảm các khoản cho vay khách hàng
12              (Tăng)/Giảm các khoản tiền, vàng gửi và cho vay các TCTD khác
13                            (Tăng)/Giảm các khoản về kinh doanh chứng khoán
14                                      (Tăng)/Giảm khác về tài sản hoạt động
15                    (Tăng)/Giảm nguồn dự phòng để bù bắp tổn thất các khoản
16                                                        Bất động sản đầu tư
17                                  Bồi thường thuộc phần trách nhiệm giữ lại
18                                                               CHI BÁN HÀNG
19                                        CHI PHÍ QUẢN LÝ CÔNG TY CHỨNG KHOÁN

In [41]:
import json
import re
from pathlib import Path
import pandas as pd

if "df_bctc_records" not in globals():
    raise RuntimeError("Khong tim thay df_bctc_records. Hay chay cell xu ly du lieu truoc.")

# Tu dong nap mapping neu chua co trong kernel
if "ind_map_exact" not in globals() or "ind_map_norm" not in globals() or "norm_text" not in globals():
    def norm_text(text: object) -> str:
        s = "" if text is None else str(text).strip().lower()
        s = re.sub(r"\s+", " ", s)
        return s

    mapping_file_candidates = [
        Path(r"d:/project/lakehouse_ptich_ck/etl/airflow/plugins/logic/bctc.md"),
        Path(r"d:/project/web_ptich_ck/md/bctc.md"),
        Path(r"d:/project/lakehouse_ptich_ck/test/general/bctc_luong_2.md"),
    ]
    mapping_file = next((p for p in mapping_file_candidates if p.exists()), None)
    if mapping_file is None:
        raise FileNotFoundError("Khong tim thay file mapping ind_name -> ind_code.")

    mapping_raw = json.loads(mapping_file.read_text(encoding="utf-8"))
    ind_map_exact = {}
    ind_map_norm = {}
    for item in mapping_raw:
        name = str(item.get("ind_name", "")).strip()
        code = str(item.get("ind_code", "")).strip()
        if not name or not code:
            continue
        ind_map_exact[name] = code
        ind_map_norm[norm_text(name)] = code

    print(f"Da nap mapping: {mapping_file} | so entries: {len(ind_map_exact):,}")

# Thuc hien gia lap mapping lai tren df_bctc_records de tim ra cac dong bi rot
temp_ind_code = df_bctc_records["ind_name"].map(ind_map_exact)
missing_mask = temp_ind_code.isna()
temp_ind_code.loc[missing_mask] = df_bctc_records.loc[missing_mask, "ind_name"].map(lambda x: ind_map_norm.get(norm_text(x)))

# Dem so ban ghi da map thanh cong
mapped_count = temp_ind_code.notna().sum()

# Trich xuat cac ban ghi co ind_code la NaN
df_unmapped = df_bctc_records[temp_ind_code.isna()].copy()

# Thong ke danh sach cac chi tieu chua duoc map va so lan xuat hien cua chung
unmapped_stats = df_unmapped["ind_name"].value_counts().reset_index()
unmapped_stats.columns = ["ind_name_chua_map", "so_lan_xuat_hien"]

# In thong ke tong quan
print(f"Tong so ban ghi (dong) xu ly         : {len(df_bctc_records):,}")
print(f"So ban ghi (dong) da map thanh cong  : {mapped_count:,}")
print(f"So ban ghi (dong) KHONG map duoc     : {len(df_unmapped):,}")
print(f"So luong chi tieu doc lap bi thieu   : {len(unmapped_stats):,}")
print("-" * 60)

# Hien thi toi da 100 chi tieu thieu
pd.set_option("display.max_rows", 100)
unmapped_stats.head(100)

Tong so ban ghi (dong) xu ly         : 695,872
So ban ghi (dong) da map thanh cong  : 695,872
So ban ghi (dong) KHONG map duoc     : 0
So luong chi tieu doc lap bi thieu   : 0
------------------------------------------------------------

Empty DataFrame
Columns: [ind_name_chua_map, so_lan_xuat_hien]
Index: []

In [42]:
import pandas as pd

if "df_bctc_records" not in globals() or "ind_map_exact" not in globals():
    raise RuntimeError("Không tìm thấy df_bctc_records hoặc dictionary mapping.")

# ==========================================
# THỰC HIỆN MAPPING CHÍNH THỨC VÀO df_bctc_records
# ==========================================

# 1. Ưu tiên 1: Map chính xác (exact)
df_bctc_records["ind_code"] = df_bctc_records["ind_name"].map(ind_map_exact)

# 2. Ưu tiên 2: Map các dòng còn thiếu (NaN) bằng cách chuẩn hóa text (norm)
missing_mask = df_bctc_records["ind_code"].isna()
df_bctc_records.loc[missing_mask, "ind_code"] = df_bctc_records.loc[missing_mask, "ind_name"].map(lambda x: ind_map_norm.get(norm_text(x)))

# 3. (Tuỳ chọn) Loại bỏ các bản ghi không có ind_code nếu bạn chỉ muốn giữ data sạch
# Nếu bạn muốn giữ lại để kiểm tra thì comment dòng này lại:
df_bctc_records = df_bctc_records.dropna(subset=["ind_code"]).copy()

print(f"Đã map xong! Tổng số bản ghi hợp lệ có trong df_bctc_records: {len(df_bctc_records):,}")

Đã map xong! Tổng số bản ghi hợp lệ có trong df_bctc_records: 695,872

In [ ]:
import pandas as pd

# Kiểm tra xem bộ dữ liệu hoàn thiện đã có trên bộ nhớ chưa
if "df_bctc_records" not in globals():
    raise RuntimeError("Không tìm thấy df_bctc_records. Hãy chạy cell mapping dữ liệu trước.")

# ==========================================
# 1. KHAI BÁO THÔNG TIN CẦN TRUY VẤN
# ==========================================
target_ticker = "VIC"
target_quarter = 4
target_year = 2025

# Tùy chọn lọc nâng cao (Để None nếu muốn lấy toàn bộ)
target_ind_name = None  # Ví dụ: "Doanh thu"
target_ind_code = None  # Ví dụ: "110" hoặc "BS_1" (Tùy theo chuẩn mã trong bctc.md)
target_report_code = 'IS'  # Ví dụ: "IS" (Nếu muốn lọc theo loại báo cáo cụ thể)

# ==========================================
# 2. XÂY DỰNG ĐIỀU KIỆN LỌC (MASK)
# ==========================================
# Lọc cơ bản (Thêm strip() để đảm bảo không rớt dữ liệu do khoảng trắng ẩn)
mask = (
    (df_bctc_records["ticker"].astype(str).str.strip().str.upper() == str(target_ticker).strip().upper())
    & (df_bctc_records["quarter"] == int(target_quarter))
    & (df_bctc_records["year"] == int(target_year))
)

# Lọc theo Tên chỉ tiêu (Tìm kiếm tương đối / Contains)
if target_ind_name:
    mask = mask & (
        df_bctc_records["ind_name"].astype(str)
        .str.contains(str(target_ind_name), case=False, na=False)
    )

# Lọc theo Mã chỉ tiêu (Tìm kiếm tuyệt đối / Exact match)
if target_ind_code:
    mask = mask & (
        df_bctc_records["ind_code"].astype(str).str.strip().str.upper() == str(target_ind_code).strip().upper()
    )

if target_report_code:
    mask = mask & (
        df_bctc_records["report_code"].astype(str).str.strip().str.upper() == str(target_report_code).strip().upper()
    )

# ==========================================
# 3. TRÍCH XUẤT VÀ HIỂN THỊ
# ==========================================
df_check = df_bctc_records.loc[mask].sort_values(
    by=["report_code", "ind_code", "ind_name"],
    na_position="last",
).reset_index(drop=True)

print(f"TRUY VẤN: Ticker={target_ticker} | Quarter={target_quarter} | Year={target_year}")
print(f"Số bản ghi tìm thấy: {len(df_check):,}")
print("=" * 60)

# Cấu hình Pandas hiển thị full dữ liệu không bị cắt ngang
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

# Hiển thị kết quả (có thể thay đổi số lượng head() nếu cần)
df_check.head(100)

TRUY VẤN: Ticker=VIC | Quarter=4 | Year=2025
Filter ind_name: None
Filter ind_code: None
Filter report_code: IS
Số bản ghi tìm thấy: 22
================================================================================

   ticker  quarter  year                                                          ind_name                                                  ind_code         value       report_name report_code
0     VIC        4  2025                                      Các khoản giảm trừ doanh thu                              cac_khoan_giam_tru_doanh_thu  1.327200e+10  income_statement          IS
1     VIC        4  2025                                                  Chi phí bán hàng                                          chi_phi_ban_hang  1.269915e+13  income_statement          IS
2     VIC        4  2025                                                      Chi phí khác                                              chi_phi_khac  2.867712e+12  income_statement          IS
3     VIC        4  2025                                                 Chi phí tài chính                                         chi_phi_tai_chinh  1.651784e+13  income_statement          IS
4     VIC        4  2025                                         Trong đó: Chi phí lãi vay                                                cp_lai_vay  8.221721e+12  income_statement          IS
5     VIC        4  2025                                      Chi phí quản lý doanh nghiệp                                                   cp_qldn  5.382229e+12  income_statement          IS
6     VIC        4  2025                                           Doanh thu thuần (1)-(2)                                           doanh_thu_thuan  1.631594e+14  income_statement          IS
7     VIC        4  2025                                     Doanh thu hoạt động tài chính                                                     dt_tc  1.060490e+13  income_statement          IS
8     VIC        4  2025                                                  Giá vốn hàng bán                                          gia_von_hang_ban  1.261517e+14  income_statement          IS
9     VIC        4  2025                                             Lợi nhuận gộp (3)-(4)                                                    ln_gop  3.700768e+13  income_statement          IS
10    VIC        4  2025                       Tổng lợi nhuận kế toán trước thuế (11)+(14)                                                      lntt  1.111684e+13  income_statement          IS
11    VIC        4  2025                                          Lợi nhuận khác (12)-(13)                                      loi_nhuan_khac_12_13 -2.506106e+12  income_statement          IS
12    VIC        4  2025           Lợi nhuận sau thuế của cổ đông của công ty mẹ (19)-(20)                 loi_nhuan_sau_thue_cua_co_dong_cong_ty_me  6.768417e+12  income_statement          IS
13    VIC        4  2025                    Lợi nhuận sau thuế của cổ đông không kiểm soát            loi_nhuan_sau_thue_cua_co_dong_khong_kiem_soat -3.187095e+12  income_statement          IS
14    VIC        4  2025                Lợi nhuận sau thuế thu nhập doanh nghiệp (15)-(18)                            loi_nhuan_sau_thue_thu_nhap_dn  3.581322e+12  income_statement          IS
15    VIC        4  2025  Lợi nhuận thuần từ hoạt động kinh doanh (5)+(6)-(7)+(8)-(9)-(10)      loi_nhuan_thuan_tu_hoat_dong_kinh_doanh_5_6_7_8_9_10  1.362294e+13  income_statement          IS
16    VIC        4  2025          Phần lợi nhuận hoặc lỗ trong công ty liên kết liên doanh  phan_loi_nhuan_hoac_lo_trong_cong_ty_lien_ket_lien_doanh  6.095840e+11  income_statement          IS
17    VIC        4  2025                                                     Thu nhập khác                                             thu_nhap_khac  3.616060e+11  income_statement          IS
18    VIC        4  2025                                       Chi phí thuế TNDN (16)+(17)                                                 thue_tndn  7.535513e+12  income_statement          IS
19    VIC        4  2025                                       Chi phí thuế TNDN hiện hành                                              thue_tndn_hh  7.162558e+12  income_statement          IS
20    VIC        4  2025                                        Chi phí thuế TNDN hoãn lại                                              thue_tndn_hl  3.729550e+11  income_statement          IS
21    VIC        4  2025                               Tổng doanh thu hoạt động kinh doanh                       tong_doanh_thu_hoat_dong_kinh_doanh  1.631727e+14  income_statement          IS

In [44]:
import pandas as pd
import psycopg2
from psycopg2.extras import execute_values

if "df_check" not in globals() and "df_bctc_records" not in globals():
    raise RuntimeError("Khong tim thay dataframe nguon. Hay chay cac cell truoc.")

# =========================================================
# KET NOI DATABASE (hoc theo pattern trong DAG/plugins)
# =========================================================
DB_URL = "postgresql+psycopg2://admin:123456@localhost:5432/postgres"
SCHEMA = "hethong_phantich_chungkhoan"
TABLE = "bctc"

# Chon nguon du lieu upsert
SOURCE_DF = "df_bctc_records"  # "df_check" hoac "df_bctc_records"

# CHE DO GIAO DICH:
# - TRANSACTION_MODE = "commit"   -> ghi that vao DB
# - TRANSACTION_MODE = "rollback" -> chay thu nghiem va rollback cuoi giao dich
TRANSACTION_MODE = "commit"

if SOURCE_DF == "df_check":
    df_upsert = df_check.copy()
else:
    df_upsert = df_bctc_records.copy()

if df_upsert.empty:
    raise ValueError("Dataframe nguon dang rong, khong co du lieu de upsert.")

required_cols = ["ticker", "year", "quarter", "ind_code", "ind_name", "value", "report_name", "report_code"]
missing_cols = [c for c in required_cols if c not in df_upsert.columns]
if missing_cols:
    raise ValueError(f"Dataframe thieu cot bat buoc: {missing_cols}")

# Chuan hoa du lieu truoc khi upsert
df_upsert["ticker"] = df_upsert["ticker"].astype(str).str.strip().str.upper()
df_upsert["quarter"] = pd.to_numeric(df_upsert["quarter"], errors="coerce").astype("Int64")
df_upsert["year"] = pd.to_numeric(df_upsert["year"], errors="coerce").astype("Int64")
df_upsert["ind_code"] = df_upsert["ind_code"].astype(str).str.strip()

# Loai bo dong khong hop le tren key
df_upsert = df_upsert.dropna(subset=["ticker", "year", "quarter", "ind_code"]).copy()
df_upsert = df_upsert[df_upsert["ind_code"] != ""].copy()

# quarter cua bang bctc dang kieu text, chuyen quarter sang chuoi de join key chinh xac
df_upsert["quarter"] = df_upsert["quarter"].astype(int).astype(str)

# Key upsert do ban tu set (KHONG dung key nao khac): (ticker, year, quarter, ind_code)
before_dedup = len(df_upsert)
df_upsert = df_upsert.drop_duplicates(subset=["ticker", "year", "quarter", "ind_code"], keep="last")
eligible_rows = len(df_upsert)
print(f"Rows truoc dedup key: {before_dedup:,} | sau dedup key: {eligible_rows:,}")

if df_upsert.empty:
    raise ValueError("Khong con du lieu hop le sau khi clean key.")

rows = [
    (
        r["ticker"],
        int(r["year"]),
        r["quarter"],
        r["ind_code"],
        r.get("ind_name"),
        None if pd.isna(r.get("value")) else float(r.get("value")),
        r.get("report_name"),
        r.get("report_code"),
    )
    for r in df_upsert.to_dict("records")
]

conn_str = DB_URL.replace("postgresql+psycopg2://", "postgresql://")
conn = psycopg2.connect(conn_str)
conn.autocommit = False

try:
    with conn.cursor() as cur:
        cur.execute("""
            CREATE TEMP TABLE temp_bctc_upsert (
                ticker TEXT,
                year INTEGER,
                quarter TEXT,
                ind_code TEXT,
                ind_name TEXT,
                value NUMERIC,
                report_name TEXT,
                report_code TEXT
            ) ON COMMIT DROP;
        """)

        execute_values(
            cur,
            """
            INSERT INTO temp_bctc_upsert
            (ticker, year, quarter, ind_code, ind_name, value, report_name, report_code)
            VALUES %s
            """,
            rows,
            page_size=1000,
        )

        # Upsert theo key user set (4 cot):
        # 1) Xoa tat ca ban ghi target trung key 4 cot
        cur.execute(f"""
            DELETE FROM {SCHEMA}.{TABLE} AS t
            USING temp_bctc_upsert AS s
            WHERE t.ticker = s.ticker
              AND t.year = s.year
              AND t.quarter::text = s.quarter
              AND t.ind_code = s.ind_code;
        """)
        replaced_count = cur.rowcount

        # 2) Chen lai ban ghi moi tu temp (la state moi nhat cua key do)
        cur.execute(f"""
            INSERT INTO {SCHEMA}.{TABLE}
            (ticker, year, quarter, ind_code, ind_name, value, report_name, report_code)
            SELECT
                s.ticker, s.year, s.quarter, s.ind_code, s.ind_name, s.value, s.report_name, s.report_code
            FROM temp_bctc_upsert AS s;
        """)
        inserted_count = cur.rowcount

        # 3) Dem so key tu dataframe da ton tai trong bang sau upsert (trong transaction hien tai)
        cur.execute(f"""
            SELECT COUNT(*)
            FROM temp_bctc_upsert AS s
            JOIN {SCHEMA}.{TABLE} AS t
              ON t.ticker = s.ticker
             AND t.year = s.year
             AND t.quarter::text = s.quarter
             AND t.ind_code = s.ind_code;
        """)
        matched_after_upsert = cur.fetchone()[0]

    affected_count = replaced_count + inserted_count

    if TRANSACTION_MODE.lower() == "commit":
        conn.commit()
        tx_result = "COMMIT"
    elif TRANSACTION_MODE.lower() == "rollback":
        conn.rollback()
        tx_result = "ROLLBACK"
    else:
        conn.rollback()
        raise ValueError("TRANSACTION_MODE chi nhan 'commit' hoac 'rollback'.")

    print("=" * 70)
    print(f"Upsert vao {SCHEMA}.{TABLE} - TX MODE: {tx_result}")
    print(f"So ban ghi dataframe thoa key upsert : {eligible_rows:,}")
    print(f"Tong rows dau vao SQL                : {len(rows):,}")
    print(f"Rows replaced (delete theo key)      : {replaced_count:,}")
    print(f"Rows inserted                        : {inserted_count:,}")
    print(f"Tong rows bi tac dong                : {affected_count:,}")
    print(f"So key ton tai trong transaction     : {matched_after_upsert:,}")
    print("Key dung de upsert: (ticker, year, quarter, ind_code)")
    if tx_result == "ROLLBACK":
        print("Luu y: Da rollback, KHONG co thay doi du lieu vinh vien trong DB.")
    print("=" * 70)

except Exception:
    conn.rollback()
    raise
finally:
    conn.close()

Rows truoc dedup key: 695,872 | sau dedup key: 630,626
======================================================================
Upsert vao hethong_phantich_chungkhoan.bctc - TX MODE: COMMIT
So ban ghi dataframe thoa key upsert : 630,626
Tong rows dau vao SQL                : 630,626
Rows replaced (delete theo key)      : 383,220
Rows inserted                        : 630,626
Tong rows bi tac dong                : 1,013,846
So key ton tai trong transaction     : 630,626
Key dung de upsert: (ticker, year, quarter, ind_code)
======================================================================